window.CMS_SEED_DATA = {
  copyVersion: 5,
  pageSettings: [
    {
      id: "page-home",
      title: "Edimax Group 整合集團能力，承接企業與營運商的網路需求。",
      eyebrow: "Edimax Group",
      summary:
        "從品牌網通設備、寬頻通訊、OEM/ODM 製造到智慧場域與數位平台，訊舟集團以多家公司分工，協助客戶更快找到合適的產品、技術與導入團隊。",
      primaryCtaLabel: "查看解決方案",
      primaryCtaHref: "#solutions",
      secondaryCtaLabel: "認識集團成員",
      secondaryCtaHref: "#companies",
      companiesEyebrow: "Group Capabilities",
      companiesTitle: "集團成員與能力矩陣",
      companiesSummary: "整合各公司角色、產品線與專業能力，讓客戶能快速判斷需求應由哪個團隊承接。",
      solutionsEyebrow: "Solutions & Proof",
      solutionsTitle: "解決方案與導入實績",
      solutionsSummary:
        "每個方案整合適用場景、參與公司與可公開的導入情境，讓客戶能從需求快速對應到可落地的集團能力。",
      contactEyebrow: "Contact",
      contactTitle: "有產品、規格或專案需求，歡迎與我們聯繫。",
      published: true,
    },
  ],
  companies: [
    {
      id: "company-edimax",
      title: "訊舟科技 Edimax",
      shortName: "Edimax",
      summary: "提供 Wi-Fi、網路設備與相關產品線，支援企業採購、通路銷售與長期供貨需求。",
      tags: ["品牌", "網通設備", "全球通路"],
      logo: "logo/edimax logo.png",
      url: "https://www.edimax.com/edimax/global",
      published: true,
    },
    {
      id: "company-acelink",
      title: "Acelink",
      shortName: "Acelink",
      summary: "提供 OEM/ODM 製造、供應鏈管理與量產服務，支援客製規格與穩定交付。",
      tags: ["代工品牌", "供應鏈", "量產交付"],
      logo: "logo/acelink logo.png",
      url: "https://www.acelink.com.tw/",
      published: true,
    },
    {
      id: "company-comtrend",
      title: "康全電訊 Comtrend",
      shortName: "Comtrend",
      summary: "提供寬頻接取、CPE 與電信設備，支援營運商與服務商的網路建置需求。",
      tags: ["寬頻", "電信設備", "CPE"],
      logo: "logo/comtrend logo.png",
      url: "https://www.comtrend.com/index.htm",
      published: true,
    },
    {
      id: "company-abst",
      title: "歐科電信 ABST",
      shortName: "ABST",
      summary: "支援電信與企業專案導入，包含需求確認、系統串接與現場整合服務。",
      tags: ["電信應用", "專案導入", "場域整合"],
      logo: "logo/abst logo.png",
      url: "https://www.abst.com.tw/",
      published: true,
    },
    {
      id: "company-smax",
      title: "訊奇 SMAX",
      shortName: "SMAX",
      summary: "提供智慧應用與軟硬體整合，協助場域串接設備、感測資料與管理介面。",
      tags: ["智慧應用", "系統整合", "IoT"],
      logo: "logo/smax logo.png",
      url: "https://www.smax.com.tw/",
      published: true,
    },
    {
      id: "company-nimbletech",
      title: "捷創數位 NimbleTech",
      shortName: "NimbleTech",
      summary: "提供數位平台、資料服務與前後台介面，支援設備管理與營運流程數位化。",
      tags: ["數位平台", "資料服務", "後台系統"],
      logo: "logo/nimbletech logo.png",
      url: "https://www.nimbletech.com.tw/",
      published: true,
    },
    {
      id: "company-iti",
      title: "銓智科 ITI",
      shortName: "ITI",
      summary: "提供技術支援、方案評估與驗證服務，協助處理特殊規格與跨團隊整合需求。",
      tags: ["技術單位", "專業支援", "集團資源"],
      logo: "logo/iti logo.png",
      url: "",
      published: true,
    },
  ],
  solutions: [
    {
      id: "solution-smart-building",
      title: "智慧建築網路整合",
      summary: "適用於商辦、住宅與園區，整合網路設備、連線管理與維運服務。",
      scenarios: ["商辦大樓", "住宅社區", "企業園區"],
      capabilities: ["Wi-Fi 規劃", "設備供貨", "場域整合", "管理平台"],
      participants: ["Edimax", "Acelink", "SMAX", "NimbleTech"],
      relatedCases: ["case-campus-iot"],
      image: "images/solutions-pages/smart-building-network.jpg",
      accent: "red",
      published: true,
    },
    {
      id: "solution-broadband",
      title: "寬頻通訊設備方案",
      summary: "提供 CPE、寬頻接取與客製設備選項，支援營運商與通路夥伴導入。",
      scenarios: ["電信營運商", "寬頻服務商", "客製設備專案"],
      capabilities: ["CPE 設備", "韌體設定", "量產交付", "在地導入"],
      participants: ["Comtrend", "Acelink", "Edimax", "ABST"],
      relatedCases: ["case-broadband-custom"],
      image: "images/solutions-pages/broadband-communication.jpg",
      accent: "blue",
      published: true,
    },
    {
      id: "solution-aiot",
      title: "AIoT 場域應用",
      summary: "整合感測設備、連線、資料管理與應用平台，支援企業場域管理。",
      scenarios: ["智慧園區", "設備監測", "環境資料管理"],
      capabilities: ["感測串接", "資料平台", "管理介面", "技術驗證"],
      participants: ["SMAX", "ITI", "NimbleTech"],
      relatedCases: ["case-campus-iot", "case-group-cms"],
      image: "images/solutions-pages/aiot-field-application.jpg",
      accent: "green",
      published: true,
    },
    {
      id: "solution-enterprise-security",
      title: "企業網路與資安連接",
      summary: "支援企業據點、辦公室與分支場域的連線部署、設備管理與後續維運。",
      scenarios: ["企業辦公室", "多據點連線", "網路設備管理"],
      capabilities: ["企業網路", "設備管理", "技術支援", "維運服務"],
      participants: ["Edimax", "Comtrend", "ITI"],
      relatedCases: ["case-broadband-custom"],
      image: "images/solutions-pages/enterprise-security-network.jpg",
      accent: "dark",
      published: true,
    },
  ],
  cases: [
    {
      id: "case-campus-iot",
      title: "企業園區網路與 IoT 管理平台",
      type: "智慧場域",
      summary: "企業園區可整合網路設備、感測資料與管理平台，集中掌握場域狀態。",
      participants: ["Edimax", "Acelink", "SMAX", "NimbleTech"],
      relatedSolutions: ["solution-smart-building", "solution-aiot"],
      displayStatus: "可對外展示",
      publicVisible: true,
      anonymous: true,
      background: "linear-gradient(135deg, #edf4ff, #fff1f2)",
      featured: true,
      published: true,
    },
    {
      id: "case-broadband-custom",
      title: "寬頻設備客製導入",
      type: "電信應用",
      summary: "依營運商需求評估設備規格、韌體設定與在地導入服務。",
      participants: ["Comtrend", "Acelink", "ABST"],
      relatedSolutions: ["solution-broadband", "solution-enterprise-security"],
      displayStatus: "可對外展示",
      publicVisible: true,
      anonymous: true,
      background: "linear-gradient(135deg, #eef7ff, #ffffff)",
      featured: false,
      published: true,
    },
    {
      id: "case-group-cms",
      title: "方案資訊與諮詢管理",
      type: "數位平台",
      summary: "集中管理方案內容、案例與聯繫資訊，讓訪客更容易找到下一步。",
      participants: ["NimbleTech", "Edimax"],
      relatedSolutions: ["solution-aiot"],
      displayStatus: "規劃中",
      publicVisible: false,
      anonymous: true,
      background: "linear-gradient(135deg, #fff6f6, #ffffff)",
      featured: false,
      published: true,
    },
  ],
};
